print("Cambio A")
print("dddd")
print("333")
print("cambio c")
print("dwdwdw")
print("Cambio Nuevo")
print("sasasa")
print("seqwdqdqdqdqdxxxxxqdqdqdqdq")
print("Hswsw")
print("e32edww")
print("ee2e2")
print("Cambio A")
print("sasa")
print("dddd")
print("333")
print("cambio c")
